name: Deploy to AWS EKS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin [ACCOUNT_ID].dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t hello-eyego .
          docker tag hello-eyego:latest [ACCOUNT_ID].dkr.ecr.us-east-1.amazonaws.com/hello-eyego
          docker push [ACCOUNT_ID].dkr.ecr.us-east-1.amazonaws.com/hello-eyego

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name hello-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
